// [START declaration]

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: spade.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Define empty message for functions returning nil
type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spade_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_spade_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_spade_proto_rawDescGZIP(), []int{0}
}

type PublicParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	N int64  `protobuf:"varint,1,opt,name=N,proto3" json:"N,omitempty"` // n number of users
	M int64  `protobuf:"varint,2,opt,name=M,proto3" json:"M,omitempty"` // m maximum size of plaintext vector
	Q []byte `protobuf:"bytes,3,opt,name=Q,proto3" json:"Q,omitempty"`  // Store q as bytes
	G []byte `protobuf:"bytes,4,opt,name=G,proto3" json:"G,omitempty"`  // Store g as bytes
}

func (x *PublicParams) Reset() {
	*x = PublicParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spade_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublicParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicParams) ProtoMessage() {}

func (x *PublicParams) ProtoReflect() protoreflect.Message {
	mi := &file_spade_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicParams.ProtoReflect.Descriptor instead.
func (*PublicParams) Descriptor() ([]byte, []int) {
	return file_spade_proto_rawDescGZIP(), []int{1}
}

func (x *PublicParams) GetN() int64 {
	if x != nil {
		return x.N
	}
	return 0
}

func (x *PublicParams) GetM() int64 {
	if x != nil {
		return x.M
	}
	return 0
}

func (x *PublicParams) GetQ() []byte {
	if x != nil {
		return x.Q
	}
	return nil
}

func (x *PublicParams) GetG() []byte {
	if x != nil {
		return x.G
	}
	return nil
}

var File_spade_proto protoreflect.FileDescriptor

var file_spade_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x73, 0x70, 0x61, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x73,
	0x70, 0x61, 0x64, 0x65, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x22, 0x46, 0x0a, 0x0c, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x73, 0x12, 0x0c, 0x0a, 0x01, 0x4e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01, 0x4e,
	0x12, 0x0c, 0x0a, 0x01, 0x4d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01, 0x4d, 0x12, 0x0c,
	0x0a, 0x01, 0x51, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x01, 0x51, 0x12, 0x0c, 0x0a, 0x01,
	0x47, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x01, 0x47, 0x32, 0x41, 0x0a, 0x07, 0x43, 0x75,
	0x72, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x36, 0x0a, 0x05, 0x53, 0x65, 0x74, 0x75, 0x70, 0x12, 0x18,
	0x2e, 0x73, 0x70, 0x61, 0x64, 0x65, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x1a, 0x11, 0x2e, 0x73, 0x70, 0x61, 0x64, 0x65,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x42, 0x04, 0x5a,
	0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_spade_proto_rawDescOnce sync.Once
	file_spade_proto_rawDescData = file_spade_proto_rawDesc
)

func file_spade_proto_rawDescGZIP() []byte {
	file_spade_proto_rawDescOnce.Do(func() {
		file_spade_proto_rawDescData = protoimpl.X.CompressGZIP(file_spade_proto_rawDescData)
	})
	return file_spade_proto_rawDescData
}

var file_spade_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_spade_proto_goTypes = []interface{}{
	(*Empty)(nil),        // 0: spadeproto.Empty
	(*PublicParams)(nil), // 1: spadeproto.PublicParams
}
var file_spade_proto_depIdxs = []int32{
	1, // 0: spadeproto.Curator.Setup:input_type -> spadeproto.PublicParams
	0, // 1: spadeproto.Curator.Setup:output_type -> spadeproto.Empty
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_spade_proto_init() }
func file_spade_proto_init() {
	if File_spade_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_spade_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spade_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublicParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_spade_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_spade_proto_goTypes,
		DependencyIndexes: file_spade_proto_depIdxs,
		MessageInfos:      file_spade_proto_msgTypes,
	}.Build()
	File_spade_proto = out.File
	file_spade_proto_rawDesc = nil
	file_spade_proto_goTypes = nil
	file_spade_proto_depIdxs = nil
}
